export const testIDs = {
  TAB_VIEW_MOVIE: 'TAB_VIEW_MOVIE',
  TAB_VIEW_FAVORITE: 'TAB_VIEW_FAVORITE',
  TAB_VIEW_BOOKED: 'TAB_VIEW_BOOKED',
  //Bottom Tab
  BOTTOM_TAB_HOME: 'BOTTOM_TAB_HOME',
  BOTTOM_TAB_BOOK_TICKET: 'BOTTOM_TAB_BOOK_TICKET',
  //Button List movie
  BTN_LIKE_TAB_MOVIE: 'BTN_LIKE_TAB_MOVIE_',
  BTN_BOOK_TICKET_TAB_MOVIE: 'BTN_BOOK_TICKET_TAB_MOVIE_',
  BTN_LIKE_TAB_FAVORITE: 'BTN_LIKE_TAB_FAVORITE_',
  BTN_BOOK_TICKET_TAB_FAVORITE: 'BTN_BOOK_TICKET_TAB_FAVORITE_',
  BTN_LIKE_TAB_BOOKED: 'BTN_LIKE_TAB_BOOKED_',
  BTN_BOOK_TICKET_TAB_BOOKED: 'BTN_BOOK_TICKET_TAB_BOOKED_',
  BTN_BOOK_TICKET : 'BTN_BOOK_TICKET',
  //List
  LIST_MOVIE: 'LIST_MOVIE',
  LIST_FAVORITE: 'LIST_FAVORITE',
  LIST_BOOKED: 'LIST_BOOKED',
};

export default testIDs;
